### ISSUE TITLE
how can i use this file

### ISSUE THREAD

**Issue by hennn** [flowplayer/flowplayer-hlsjs#10]
hi
I'm beginner and i want to setup this project on flowplayer in wordpress but i dont understand anything of this project
please explain me how can i do this?
thanks.

**Comment by blacktrash** [comment]
@hennn - please don't take this the wrong way, but as this is a bug tracker, your port of call is our public forum https://flowplayer.org/forum for usage questions, not least in fairness to other users who may profit from the answers. If you're using our Flowplayer WordPress plugin (recommended) https://wordpress.org/plugins/flowplayer5/ then even better turn to its support forum: https://wordpress.org/support/plugin/flowplayer5

It's really easy, the plugin just has to be loaded after the usual Flowplayer assets: https://github.com/flowplayer/flowplayer-hlsjs#usage - but I'm afraid, I can't tell you what's the easiest way to do this in WordPress.

Thank you.

**Comment by hennn** [comment]
where is the assets of flowplayer?
wp-content/plugins/flowplayer5/admin/assets?
plugins/flowplayer5/frontend/assets?
i'm very beginner in this work, 
how can play this file by flowplayer?
http://216.126.193.9/live/video/adab-marefat.m3u8
please explain me by an example
thanks.

**Comment by blacktrash** [comment]
As I said, I'm not familiar with WordPress, please ask your question at https://wordpress.org/support/plugin/flowplayer5
