### ISSUE TITLE
Is this needed now that 7.2 includes hls.js?

### ISSUE THREAD

**Issue by shaharmor** [flowplayer/flowplayer-hlsjs#101]

**Comment by bbbo** [comment]
7.2 does not include hls.js but a slim engine which can directly use the hls.js (or hls.light.js) client libraries.

You have two options: load hls.js / hls.light.js (resp. the minified versions)  _before_ flowplayer.min.js  and FP 7.2 will use them with the integrated lite engine, or load _our_ flowplayer.hlsjs.min.js / flowplayer.hlsjs.light.min.js plugins _after_ flowplayer.min.js to use the FP-specific plugins.

We'll add better documentation shortly.
