### ISSUE TITLE
Internal error happened while processing hlsKeyLoaded:Cannot call a class as a function

### ISSUE THREAD

**Issue by Beslinda** [flowplayer/flowplayer-hlsjs#104]
I am using  flowplayer.hlsjs.min.js in my web app. When I run the the web app locally it works fine, when I build it I get the following error:
`Internal error happened while processing hlsKeyLoaded:Cannot call a class as a function`

I do have flowplayer.js script before the flowplayer.hlsjs.min.js

**Comment by nnarhinen** [comment]
A link to a sample page would be needed.

**Comment by Beslinda** [comment]
BTW this does not happen in safari. In Safari it works fine but the rest of the browsers no.
I will try to set up a plunkr

**Comment by nnarhinen** [comment]
Yeah, Safari does not use HLS.js by default.

**Comment by Beslinda** [comment]
I use flowplayer 6.0.2 cannot reproduce on plunker.

**Comment by Beslinda** [comment]
Found the problem. I was minifying the already minified script during build. 
Thanks for responding
