### ISSUE TITLE
Videos with hlsjs plugin do not play on windows 7, IE11

### ISSUE THREAD

**Issue by Beslinda** [flowplayer/flowplayer-hlsjs#106]
I use flowplayer  6.0.2 with hlsjs plugin to play videos without flash and it works fine in all browser except windows 7 running IE11. (windows 10, IE11 works fine also)

This is the following error I get: 
HTML5: UNNSUPORTED VIDEO FORMAT. Try installing adobe flash.

Is flowplayer-hlsjs supported on windows 7, IE11 ???

**Comment by bbbo** [comment]
See my answer in the forums. You cannot play HLS in any IE version on Windows 7 or below since Microsoft never implemented the required Media Source Extensions.
