### ISSUE TITLE
Official live stream demo isn't working?

### ISSUE THREAD

**Issue by huanghe2015** [flowplayer/flowplayer-hlsjs#108]
Looks like m3u8 live stream address in demo isn't working:
https://nasa-i.akamaihd.net/hls/live/253565/NASA-NTV1-Public/master.m3u8
Can you change one new?

**Comment by bbbo** [comment]
NASA disabled external access. We're looking for a new stream source with is available 27/7 through https.

**Comment by huaweichen** [comment]
Nah, https://demos.flowplayer.org/api/hlsjs.html

**Comment by bbbo** [comment]
that link is outdated ;) 
You can use http://demos.flowplayer.org/plugins/hlsjs.html (not the https link) for now.
