### ISSUE TITLE
Unminified versions of the library don't appear to function

### ISSUE THREAD

**Issue by JoeDuncko** [flowplayer/flowplayer-hlsjs#112]
Trying out flowplayer-hlsjs versions, it appears that from the CDN `//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.js` doesn't work for me in the newest version of FF (without flash installed) but the minified version at `//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js` does.

Codepen with the minified version (working): https://codepen.io/anon/pen/wmwpYj

Codepen with the unminified version (not working): https://codepen.io/anon/pen/GxKyGv

This is an issue because we want to manage our libraries using npm, and this repository doesn't include the minified versions. Are you not supposed to use the non-minified versions of the library?

**Comment by bbbo** [comment]
The unminified versions contain *only* the engine plugin, not the hls.js client library. You'll either have to load hls.js in *addition* , or package it into the plugin (see the Makefile in the repo).

The plugin hasn't been developed for a while though, so we rather recommend to use the hlsjs-lite engine integrated in current player versions. 7.2.5 add event listeners so it has almost the feature set of the external plugin now, minus multiple audio renditions and subtitle support (coming soon).

https://flowplayer.com/docs/player/setup#hlsjs-lite

**Comment by JoeDuncko** [comment]
Thanks @bbbo ! It's a little disheartening to hear that as right on line 15 `flowplayer.hlsjs.js` says it includes `hls.js`. https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L15

I'll move to using `hls.js` directly instead, as you suggest. Thanks again!

**Comment by bbbo** [comment]
that's because it _will_ contain the library after running make ;)
