### ISSUE TITLE
hlsjs.light.js - bufferWhilePaused not working

### ISSUE THREAD

**Issue by Sportradar-KK** [flowplayer/flowplayer-hlsjs#115]
Hi flowplayer team,
 
I have noticed that the hls option for bufferWhilePaused is not working with the new hls.light.min.js and 7.2.5. 
With classic flowplayer.hlsjs.min.js it works like expected. Is this a wanted behavior or is this a bug?
If it’s a bug please tell me about your time estimation to get this fixed. 
 
hlsjs : {
    safari : true,
    debug: false,
    bufferWhilePaused: false,
},
 
 
My setup:
Flowplayer 7.2.5 with flowplayer.hlsj.min.js (v1.1.1-42-g4295710)
Windows 10
Chrome 66.0.3359.181

**Comment by bbbo** [comment]
Please see https://github.com/flowplayer/flowplayer/issues/1388 . Will be addressed in FP 7.2.7

**Comment by carrbrpoa** [comment]
Hey @bbbo, I'm with 7.2.7 and still see the streaming is trying to load, even after `bufferWhilePaused = false` and calling `pause()` of API.

Chunks of code:
HTML:
```
<div id="videoPlayer" class="no-volume is-live is-splash"
	style="background-color:#FFF; background-size:25%; background-position:75% 75%">
</div>
```

Typescript:

When initializing player:

```
initVideoPlayer() {
	var videoContainer = document.getElementById('videoPlayer');
	this.videoAPI = flowplayer(videoContainer, {
			share: false,
			ratio: "0.5625",
			rtmp: "rtmps://.../",
			qualities: "240p,480p",
			"default-quality": "240p",
			clip: {
				//sources: []
			},
			bufferWhilePaused: false //not sure
		});
	this.videoAPI.bufferWhilePaused = false; //not sure
}
```

The follow is called on every video load:

```
private loadVideo(videoName, url) {
	this.videoAPI.load({
		title: "Ao vivo",
		sources: [{
				type: "application/x-mpegurl",
				src: url
			}, {
				type: "video/flash",
				src: `${videoName}.stream`
			},
		]
	});
}
```

While inspecting `this.videoAPI`:

![image](https://user-images.githubusercontent.com/10212618/45757272-55785380-bbf9-11e8-9d85-d47236d90aff.png)

I'm doing something wrong?
Thanks in advance!

PS: I'm using Angular 6, but don't believe it is related. Maybe bad configuration.

**Comment by carrbrpoa** [comment]
I know it's still trying because my app stops the streaming on my server and after the `this.videoAPI.pause()`, I see in console:

![image](https://user-images.githubusercontent.com/10212618/45758044-19de8900-bbfb-11e8-932f-cd4bc54aaf1e.png)

**Comment by bbbo** [comment]
Link to a public minimal (player setup only) sampel page please.

bufferWhilePaused is not a player option but belongs into the hlsjs: {} configuration object. See the  hlsjs parametrs in https://flowplayer.com/help/developers/flowplayer-7/setup#hls

**Comment by carrbrpoa** [comment]
Seems it is working as expected now.
Changed the initializer code:
```
this.videoAPI = flowplayer(videoContainer, {
		share: false,
		ratio: "0.5625",
		rtmp: "rtmps://.../",
		qualities: "240p,480p",
		"default-quality": "240p",
		clip: {
			//sources: []
		},
		bufferWhilePaused: false //not sure
	});
this.videoAPI.bufferWhilePaused = false; //not sure
```
...for:
```
this.videoAPI = flowplayer(videoContainer, {
	live: true,
	share: false,
	ratio: "0.5625",
	rtmp: "rtmps://.../",
	qualities: "240p,480p",
	"default-quality": "240p",
	clip: {
		hlsjs: {
			bufferWhilePaused: false
		}
	}
});
```

Thanks! Took some time to realize where should I put that `hlsjs` config object, though.

**Comment by bbbo** [comment]
That is shown right in the doc?
Anyway, good you got it working. Note: the "qualities" settings have no meaning if you just have a HLS stream.

**Comment by carrbrpoa** [comment]
It is, indirectly, I guess. If you increment an exemple like this one on docs...
```
clip: {
	flashls: {
		// limit amount of retries to load hls manifests in Flash
		manifestloadmaxretry: 2
	},
	sources: [{
			type: "application/x-mpegurl",
			src: "//path/to/your.m3u8"
		}
	]
}
```
with one or other `hlsjs` config prop besides `flashls` and `sources`, would be more clear for distracted users like me :smiley:. Btw, didn't see any of those in whole docs, except that `hlsjs` config object with `xhrSetup` in player's "root" config.
