### ISSUE TITLE
for cyclic loading hlsjs video

### ISSUE THREAD

**Issue by Machacek76** [flowplayer/flowplayer-hlsjs#117]
Why don't load hls video if splash image has e404 error? Hlsjs plugin load hls video and again and the source is ready status200. This trouble is only with hls video the source while playing mp4 video isn't trouble

**Comment by bbbo** [comment]
Please check https://github.com/flowplayer/flowplayer-hlsjs/blob/master/README.md

This plugin is deprecated. Use the hlsjs-lite engine instead.

**Comment by Machacek76** [comment]
yes I do use this version hlsjs

   Includes hls.light.js
   Requires Flowplayer HTML5 version 7 or greater
   v1.1.1-42-g4295710

**Comment by bbbo** [comment]
As I said and as documented in the readme I linked to: the external plugin has been deprecated a long time ago. You need to use the original hls.js *library* with the hlsjs-lite engine integrated into Flowplayer 7.2.x, as  explained in https://flowplayer.com/help/developers/flowplayer-7/setup#hlsjs-lite .
