### ISSUE TITLE
Live stream and #EXT-X-ENDLIST problem

### ISSUE THREAD

**Issue by FDiskas** [flowplayer/flowplayer-hlsjs#12]
Pay attention how flash version is working. Then I put `#EXT-X-ENDLIST` at the end of m3u8 file - this playlist not loaded any more. This is how it should work. And the html5 version is still requesting the playlist file
Flash version: https://youtu.be/-8MwEnrjIPM
HTML5 version: https://youtu.be/KuyV2kggwAQ

**Comment by FDiskas** [comment]
Here is some functionaliti in https://github.com/dailymotion/hls.js/blob/master/src/loader/playlist-loader.js#L128

**Comment by blacktrash** [comment]
What you're asking for specifically is support for event playlists: https://developer.apple.com/library/ios/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-EVENT_PLAYLIST with `#EXT-X-PLAYLIST-TYPE:EVENT`
Did you check whether this works in hls.js alone: http://dailymotion.github.io/hls.js/demo/ ?

On a more general note: What is certainly missing from the plugin is integration of the hls.js API, whether its methods or events.
We are currently discussing the best ways to do this, not only for this plugin. Once we have fleshed out a concept which adapts itself best to the core player and is not bound to break at the next turn of core development, this will be added step by step to the plugin.
It's the next step, but it will take a while.

**Comment by blacktrash** [comment]
@FDiskas - can you check with the latest plugin version?
The hls.js code you referenced was not yet in the packed version of the plugin (very recent).

**Comment by FDiskas** [comment]
Perfect. Works. Thanks

**Comment by blacktrash** [comment]
Good to hear.
Out ouf curiousity: Do you have server statistics how this behaves in generic HLS? Safari doesn't reveal this in the network console, maybe your server statistics tell you?

And, to rub it in: if you happen to have a live stream with the right CORS settings server side and which we are allowed to use in a demo, do not hesitate to contact us ;-)

Thanks.

**Comment by FDiskas** [comment]
Sorry - all stream urls are private.
About network requests - try using Google Chrome. It shows flash and html5 requests.

**Comment by blacktrash** [comment]
@FDiskas - no prob, but I'd better ask ;-)
Nah, Google Chrome doesn't show me _generic_ HLS. I wanted to check how that behaves.
Anyway, closing this.

**Comment by FDiskas** [comment]
You could try this `http://nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8`

**Comment by blacktrash** [comment]
Been there, but: https://github.com/dailymotion/hls.js/issues/23

**Comment by blacktrash** [comment]
Currently it seems to work (famous last words), thanks for reminding me. Will check a bit more.

**Comment by blacktrash** [comment]
Nah, Firefox still a problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1208035
