### ISSUE TITLE
NPM or Bower

### ISSUE THREAD

**Issue by FDiskas** [flowplayer/flowplayer-hlsjs#13]
How to install this using `npm` or `bower` ?

**Comment by FDiskas** [comment]
Sorry duplicate #8
probably needs to be described in readme

**Comment by blacktrash** [comment]
https://github.com/flowplayer/flowplayer-hlsjs#commonjs
https://github.com/flowplayer/flowplayer-hlsjs#building-the-plugin
?

**Comment by FDiskas** [comment]
To complicated. To many dependencies. Please add to bower with "dist" folder with compiled and minified version

**Comment by nnarhinen** [comment]
If you are using npm with browserify or webpack, you can just run

```
npm install flowplayer flowplayer/flowplayer-hlsjs
```

then in your javascript code you do

```js
var flowplayer = require('flowplayer');
require('flowplayer-hlsjs'); // Plugin gets injected to flowplayer

flowplayer('#mydiv', myConf);
```

We can look into publishing this also to bower

**Comment by FDiskas** [comment]
I dont use browserify or webpack or requirejs so I cant use `require()` function

**Comment by kudoz83** [comment]
Found this thread via Google and it was only mildly useful.   This should get documented somewhere...

To install flowplayer 6.05 and flowplayer-hls 1.03 via npm and use with systemjs and systemjs-builder.

Install via NPM
`npm install flowplayer flowplayer/flowplayer-hlsjs`

gulp-copy file structure (result)
```
lib
-flowplayer
--hls.js
---flowplayer.hlsjs.js
---hls.js
--flowplayer.js
```

systemjs.config.js
```
map: {
     'flowplayer': 'lib/flowplayer/',
     'flowplayer-hlsjs': 'lib/flowplayer/hls.js/',
     'hls.js/lib/index.js': 'lib/flowplayer/hls.js/hls.js'
}, packages: {
     'flowplayer': { main: 'flowplayer', defaultExtension 'js' },
     'flowplayer-hls': { main: 'flowplayer.hlsjs', defaultExtension: 'js' }
}
```
import / require
```
var flowplayer = require('flowplayer');
var engine = require('flowplayer-hlsjs');
engine(flowplayer);
```

usage
`var instance = flowplayer($el, config);`

Note there is a JQuery dependency that I didn't cover above, but make sure it is part of your systemjs package.

**Comment by RopoMen** [comment]
Relates https://github.com/flowplayer/flowplayer/issues/1131
