### ISSUE TITLE
Video streams, but no audio (mp4/aac)

### ISSUE THREAD

**Issue by janiszie** [flowplayer/flowplayer-hlsjs#14]
When video is streamed through hlsjs engine (from common desktop browsers lastest Chrome/FF/IE11) there is no audio. When video streams through html5 engine (iOS Safari) sound is OK.

You can check here: http://94.101.229.216/test/html5.html

For simplicity in m3u8 file I left only one bandwidth version, streaming is provided by Adobe Streaming server.

Yet there is no codec version in m3u8 file but I tried different ones, no change. I understand that hlsjs tries to guess right encoding if codec information is not provided.

mp4 file is encoded with this settings:

===================== Video =====================
Id                          : 1
Format                      : AVC
Format info                 : Advanced Video Codec
Format profile              : High@L3.1
Use of CABAC                : Yes
RefFrames                   : 4 frames
Codec Id                    : avc1
Codec info                  : Advanced Video Coding
Duration (ms)               : 12mn 38s
Bitrate mode                : Variable

===================== Audio =====================
Id                          : 2
Format                      : AAC
Format info                 : Advanced Audio Codec
Format profile              : LC
Codec Id                    : 40
Duration (ms)               : 12mn 38s
Source_Duration/String      : 12mn 38s
Bitrate mode                : Variable
Bitrate                     : 192 Kbps
Bitrate maximum             : 297 Kbps
Channel(s)                  : 2 channels
ChannelPositions            : Front: L R
Sampling rate               : 48.0 KHz
Compression_Mode/String     : Lossy

**Comment by blacktrash** [comment]
The same happens with hls.js alone: http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2F94.101.229.216%2Ftest%2Fplaylist1943.m3u8
I can't see any obvious problem with your stream, and it plays in generic HLS, so may I ask you to take this to the hls.js bug tracker: https://github.com/dailymotion/hls.js/issues - the plugin cannot make it work, if the hls.js client can't.
Thank you.

**Comment by janiszie** [comment]
Thank you. I did that now https://github.com/dailymotion/hls.js/issues/61

**Comment by tarkanlar** [comment]
I got the same issue when i make livestream with mp3 there was no sound in chrome but there was sound in safari and ios then i switched to acc it worked both chrome and safari but what is wrog with mp3?
