### ISSUE TITLE
update total duration in seek bar to add ability to seek in live HLS playlist with new chunks added after playback starts

### ISSUE THREAD

**Issue by muxketeer** [flowplayer/flowplayer-hlsjs#19]
I have a live HLS playlist.  The playlist has segments being added to it every 10 seconds.  When I open the live m3u8 up and play it in flowplayer with the flowplayer-hls plugin , it nicely lets me seek anywhere in the stream for the number of chunks that existed when the palyer was intiated.  the problem is that after some time the m3u8 playlist is longer than what is reported in the seek bar.  

By way of example, lets say when I start to play the .m3u8 it has 4 minutes worth of video.  The far right of the seek bar lets me get to 4 minutes in the .m3u8.  1 minute later the .m3u8 has had 1 minute of video added to it, so now the .m3u8 has 5 minutes of video.  So the .m3u8 that is being played will play for 5 minutes, but since at load time the playlist only had 4 minutes, I can only seek to the first 4 minutes in the flowplayer seek bar.  

Is there a way to get this plugin check the currently playing .m3u8 and update the total duration reported in the seek bar?

**Comment by blacktrash** [comment]
HLS live DVR is not yet implemented in the core player: https://github.com/flowplayer/flowplayer/issues/950
For the moment you have to make do with setting `live: true` for player or clip, which has, among other things, the effect that there's no timeline in the controlbar, see http://demos.flowplayer.org/basics/live.html
For consistency this will be implemented for the hlsjs plugin once the core player supports HLS live DVR.

**Comment by muxketeer** [comment]
I think live HLS functionality may be in the HLSjs framework to some extent.  As I'm able to get DVR functionality when playing a live HLS playlist (with the exception of the above mentioned issue).

I'm getting around the CORS issue by using my own nginx server equiped with the rtmp/hls plugin. 
Basically, the flow of events in my test to simulate a live event is : 
1.start encoding a 1 hour video (via ffmpeg) and have the output stream to my nginx server, via rtmp. 
2. nginx server creates live adaptive hls playlist out of incoming rtmp stream(s).
3. flowplayer, with hlsjs plugin, plays back the live HLS playlist hosted on private nginx server, as if it were a live event. 

I'm happy to send you my ffmpeg commands and even a Docker container containing the setup of my nginx+HLS module server (if you're into the current Docker craze : ) ), if you want to duplicate when taking a look into the above mentioned issue. 

FYI, I'm able to get somewhat of a DVR functionality in my live HLS .m3u8 with the following configuration of the player. (with the exception of what I detailed in OP) 

window.onload = function () {

  flowplayer("#hlsjs", {
    splash: true,
    embed: false, // setup would need iframe embedding
    ratio: 5/12,

    clip: {
      sources: [
        { type: "application/x-mpegurl",
          src:  "//<nginx hls server>/live_hls/hlsdvr.mp4_groundcontrol54321.m3u8" }
        
      ]
    }

  }).on("ready", function (e, api, video) {
    // info for demo purposes
    document.getElementById("engine").innerHTML = api.engine.engineName;
    document.getElementById("vtype").innerHTML = video.type;
    document.getElementById("src").innerHTML = video.src;

  });

};

**Comment by blacktrash** [comment]
hlsjs would have to do similar things as the core player in generic hls playback, therefore we'll wait until this is implemented in the core player; to avoid needless duplication of code etc.

Thanks for sharing your test setup, but experience tells that to get reasonably solid testing environment we also need a 'real' live stream. I can sort of get something similar to your setup with ffserver, but usually that's not enough.

**Comment by popler** [comment]
@blacktrash I can give you access to live stream with Wowza and/or Nimble server for DVR testing. I'm really insterested in this functionality:)

**Comment by blacktrash** [comment]
@popler - thank you; as already mentioned, I'll get back once this is implemented in core. You can vote up https://github.com/flowplayer/flowplayer/issues/950 ;-)

**Comment by muxketeer** [comment]
To be clear, here's the live DVR functionality that is already working in this framework:
with a the Live playlist in this state when playback starts:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:10
#EXT-X-PLAYLIST-TYPE: EVENT
#EXT-X-DISCONTINUITY
#EXTINF:10.010,
0.ts
#EXTINF:1.477,
1.ts
#EXT-X-DISCONTINUITY
#EXTINF:10.010,
2.ts
#EXTINF:10.010,
3.ts
...
#EXTINF:10.010,
30.ts

```
the play head looks like this:
![playhead_current](http://s7.postimg.org/8rtnumje3/current_Time_And_Seeking_playhead.png)
 notice the time on the left is less than the time on the right. :

a minute later the same live HLS playlist looks like this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:10
#EXT-X-PLAYLIST-TYPE: EVENT
#EXT-X-DISCONTINUITY
#EXTINF:10.010,
0.ts
#EXTINF:1.477,
1.ts
#EXT-X-DISCONTINUITY
#EXTINF:10.010,
2.ts
#EXTINF:10.010,
3.ts
...
#EXTINF:10.010,
30.ts
...
#EXTINF:10.010,
37.ts

```
The player's play head looks like this while it continues to perfectly play video frames:
![playhead_future](http://s2.postimg.org/po1zi9xtl/seeking_Time_future.png)
notice that the current time (on the left) is past the total time(on the right)

For my own understanding: You are waiting for Core to create a HLS parser that updates the total duration (on the right side of the blue seek bar), dynamically, before you do so for hlsjs?

**Comment by blacktrash** [comment]
The (usually) 'sliding DVR window' must be displayed and updated. And that has to happen e.g. for generic HLS, i.e., in core, too. Then hlsjs will take over as much from core as possible.

**Comment by blacktrash** [comment]
Implemented for Flowplayer 7 which introduced DVR support. Closing.
