### ISSUE TITLE
Problems with CloudFront signed cookies

### ISSUE THREAD

**Issue by farreres** [flowplayer/flowplayer-hlsjs#21]
Greetings. I am trying to set up a CloudFront distribution for streaming HLS and as a protection layer I need to implement signed cookies. They are not working and I think it is because flowplayer-hlsjs is not activating credentials. [I have asked in hsl.js thread](https://github.com/dailymotion/hls.js/issues/246#event-545518096) here in github and they gave me this reply:

> you should be able to send cookies through this config option.
> 
> ```
> var config = {
>   xhrSetup: function(xhr, url) {
>     xhr.withCredentials = true; // do send cookies
>   }
> }
> var hls = new Hls(config);
> ```
> 

Could this be added to flowplayer-hlsjs?

**Comment by nnarhinen** [comment]
This depends on how you are initializing flowplayer, but you are able to give configuration to the underlying HLS.js instance by passing them to flowplayer in the `hlsjs` configuration key.

Example:
```js
flowplayer('#player', {
  hlsjs: { xhrSetup: function(xhr) { } }
});
```
