### ISSUE TITLE
webpack builds report errors in debug mode

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer-hlsjs#23]
In Chrome, with hlsjs.debug turned on:
```
[error] > error while initializing DemuxerWorker, fallback on DemuxerInline
```
This does not happen when a copy of dist/hls.min.js is loaded.

@nnarhinen - for the moment I will revert again to concatenating hls.min.js into the packed flowplayer.hlsjs.min.js

**Comment by blacktrash** [comment]
Additionally the error depends on node and/or npm version used:
- node v5.6.0 / npm v3.6.0: 'Uncaught TypeError: Cannot read property 'isSupported' of undefined' (`Hls` undefined) - also with node v5.4.1 / npm v3.3.12
- node v4.3.1 / npm v2.14.12: '[error] > error while initializing DemuxerWorker, fallback on DemuxerInline'

**Comment by blacktrash** [comment]
See also: https://github.com/flowplayer/work/issues/1173#issuecomment-185645968

**Comment by blacktrash** [comment]
Until solved keep webpack build in [separate branch](https://github.com/flowplayer/flowplayer-hlsjs/tree/feature/webpack).

**Comment by blacktrash** [comment]
Additionally:
With node v5.6.0 / npm v3.6.0The undefined `Hls` prevents the plugin from working at all, the error is not confined to `hlsjs.debug: true`.

**Comment by nnarhinen** [comment]
The error for `isSupported` is because we are doing `require('hls.js')['default']` which is not needed anymore. Pushed a commit for this

**Comment by nnarhinen** [comment]
The other error is already reported in dailymotion/hls.js#187 and dailymotion/hls.js#188

**Comment by blacktrash** [comment]
Sorry, that was a desperate leftover from one of my tests before I split out the feature/webpack branch again.
However, the issue with `hlsjs.debug` '[error] > error while initializing DemuxerWorker, fallback on DemuxerInline' persists with node v4.3.1 / npm v2.14.12 - I'll check whether the other ones were already caused by re-adding .default for testing.
It certainly doesn't look 100% reliable.

**Comment by nnarhinen** [comment]
As I said: the `[error] > error while initializing DemuxerWorker, fallback on DemuxerInline'` are dailymotion/hls.js#187 and dailymotion/hls.js#188

**Comment by nnarhinen** [comment]
I'll see if it's something we can fix

**Comment by nnarhinen** [comment]
Please try again

**Comment by blacktrash** [comment]
I now loaded
```js
 "dependencies": {                                                                                                     
    "hls.js": "git://github.com/dailymotion/hls.js#workerify"                                                           
  }
```
And, as I'm currently testing node v5.6.0 there's the same problem with `Hls.isSupported` not being a function.
Downgrading node again because I need it at 4.x for www

**Comment by blacktrash** [comment]
Will try your patch now.

**Comment by blacktrash** [comment]
@nnarhinen - your patch works with node v5.6.0 in a quick test - `Hls.isSupported` does not error out anymore.
Now for node v4.

**Comment by blacktrash** [comment]
@nnarhinen - seems to work with node v4 too. Great. Running some more tests. Then this can be merged.

**Comment by blacktrash** [comment]
Looking good. Thanks a lot @nnarhinen.
