### ISSUE TITLE
HLS encryption key xhr request problem on iOS and hlsjs.xhrSetup behavior on iOS

### ISSUE THREAD

**Issue by Ivars** [flowplayer/flowplayer-hlsjs#24]
Hello,

I am trying to implement encrypted video playback using the following flowplayer initialization:

```
	//element for simple log output in div	
	var log = $("#log");	

	//request to create encryption key when clicked on flowplayer
	flowplayer(function (api, root) {
	  var bean = flowplayer.bean,
	      common = flowplayer.common;
	
	  bean.on(root, "click", function () {
	    if (api.splash) {
	      // request key for movie with ID = 1000
             // this sets up PHP session and creates key entry in database
	    
	      var url = "https://www.server1.com/key/request/1000";
	      common.xhrGet(url , common.noop, common.noop);
	      
	      log.append("key request: " + url).append("<br>");
	      console.log("key request: " + url);
	    }
	  });
	});
		
	//init flowplayer
	flowplayer("#player", {
		  hlsjs: {

			xhrSetup: function(xhr, url) {
				
				xhr.withCredentials = true;		
				xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest"); 
			
				//log xhrSetup event
			    log.append(url).append("<br>");			    
			    console.log(url);									    
			    	
			} },	
	  	
	    ratio: 9/16,
	    splash: true,
	    bgcolor: "#333333",
	    embed: false,
	
	    clip: {
	      sources: [
	        { 
	        	type: "application/x-mpegurl",	
				//request m3u8 playlist from video server for movie with ID = 1000
	  			src:  "https://video.server2.com/video/1000/master.m3u8"			
	  		}	  				
	      ]
	    }
	  });
```

When initialized flowplayer loads master.m3u8 playlist which contains further playlists of encrypted TS fragments and key URI:

```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://www.server1.com/key/server/1000"
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
https://video.server2.com/video/1000/seg-1-f1-v1-a1.ts
#EXTINF:10.000,
```

Then flowplayer requests the key from here https://www.server1.com/key/server/1000, where PHP checks if there is session previously setup using call to https://www.server1.com/key/request/1000 and if it exists, then serves the key.

The problem is - this setup is working wonderfully using any desktop browser but does not work on iOS devices. 

On iOS the key request (https://www.server1.com/key/request/1000) sends correct session cookies but when flowplayer loads actual key (https://www.server1.com/key/server/1000) my server always starts new PHP session and previous page cookies are not sent.

On further investigation it seems also that on iOS xhrSetup function is not executed at all.

I have been banging my head at this for last couple days and can not find solution - is there some limitations to how I should request key on iOS? 
Maybe I should stop relying on cookies and implement some token as key url parameter:
https://www.server1.com/key/server/1000?token=xxx ?

**Comment by Ivars** [comment]
Ok, part of the problem was that iOS needs that master playlist and keys are served from the same domain:

From Apple [documentation]:(https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/DeployingHTTPLiveStreaming/DeployingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH2-SW2) 
Serving Key Files Securely Over HTTPS

The authentication domain for the key files must be the same as the authentication domain for the first playlist file. The simplest way to accomplish this is to serve the variant playlist file from the HTTPS server—the variant playlist file is downloaded only once, so this shouldn’t cause an excessive burden. Other playlist files can be served using HTTP.

But I still don't get if it's expected behavior that 

```
 hlsjs: {
            xhrSetup: function(xhr, url) {

                xhr.withCredentials = true;     
                xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest"); 

                //log xhrSetup event
                log.append(url).append("<br>");             
                console.log(url);                                       
            } },    
```

does not fire on iOS?

**Comment by nnarhinen** [comment]
I don't think iOS will use the hlsjs-plugin at all, as it does not have [support for MediaSource extensions](http://caniuse.com/#feat=mediasource). It will play HLS with the native HTML5 video tag and therefore does not use the configuration you pass in `hlsjs`.

There is some [discussion on StackOverflow](http://stackoverflow.com/questions/23874297/ios-7-safari-jwplayer-not-sending-cookie-to-load-m3u8-file-encrypted-hls-strea) about iOS limitations for key requests and cookies. Hopefully it helps you.

**Comment by blacktrash** [comment]
Indeed MediaSource is not supported on iOS, and therefore hlsjs is not either. Closing.
