### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by k1ng440** [flowplayer/flowplayer-hlsjs#27]
Hello,
I think it would be better if you use something else like ``` playOnAllBrowser ``` or something because its causing issue for us while we are testing the flowplayer on safari and microsoft edge

```
                if (hlsconf.debug) {
                    return true;
                }
```

thanks

**Comment by blacktrash** [comment]
@k1ng440, why is this causing an issue? While you're testing you're not in production? - At least that was the thought behind allowing Safari in debug mode.
I'd rather consider not allowing Safari at all until it works in hls.js. - The problem with more options is that users use them (without reading docs) - and then are annoyed that something doesn't work.
