### ISSUE TITLE
Live stream - MP3 codec 

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer-hlsjs#3]
Live stream are played without sound then mp3 codec is used

**Comment by blacktrash** [comment]
Thanks for bringing this up - I don't have a stream with mp3 available, but would not be surprised:
As this is not _generic_ HLS playback, but happens via the MediaSource extension, the transport stream segments are treated like MP4 part 10 video segments.

1. MP3 is not a valid audio codec for MP4 video.
2. You can verify this in the browser console:
```js
MediaSource.isTypeSupported('video/mp4; codecs="avc1.42c01e, mp4a.40.3"')
```
will return `false`. Whereas for instance:
```js
MediaSource.isTypeSupported('video/mp4; codecs="avc1.42c01e, mp4a.40.2"')
```
will return `true`. Similarly for `mp4a.40.5` (AAC_HE).

But indeed this should be documented.

For you, pragmatically, this may be motivation to switch to the much more efficient aac codec ;-)

**Comment by blacktrash** [comment]
Keeping this open until documented.

**Comment by popler** [comment]
Thank you for info. Problem is, that some of our users are still using MP3, as free codec in Adobe Fmle. Can I manually switch flowplayer engine between hls.js and flash hls?

**Comment by popler** [comment]
Ok, I made it with PHP. If audio codec is set to mp3 I do not load hls.js plugin. It's temporary solution but it is working:)

**Comment by blacktrash** [comment]
You can also disable the plugin for specific players on a page where the plugin is sourced by setting `hlsjs: false` in the player configuration: https://github.com/flowplayer/flowplayer-hlsjs#plugin-configuration

**Comment by mangui** [comment]
@blacktrash plz note that MP3 mime type is mp4a.40.34, audio/mp3 or audio/mpeg

**Comment by blacktrash** [comment]
@mangui - yes, I used `mp4a.40.34` in the code snippet at https://github.com/flowplayer/flowplayer-hlsjs/issues/3#issuecomment-148970822 which will correctly return `false`.
