### ISSUE TITLE
IE8 javascript error

### ISSUE THREAD

**Issue by xpepermint** [flowplayer/flowplayer-hlsjs#31]
I use the latest commercial player. When my website includes `flowplayer.hlsjs.min.js`, I see an error in `IE8`. I think it's actually the `hls.js` problem.

**Comment by blacktrash** [comment]
Thank for bringing this up - and taking it to the hls.js bug tracker. As you noticed yourself the problem is caused by hls.js.
I'll probably make a small change in the Flowplayer plugin per se, but there will still be the error(s) triggered by loading hls.js. I know what's causing this, so I propose to coninue 'over there'.
Meanwhile, the error should affect any functionality (or does it for you?) because the effect is that the hlsjs engine is not loaded, and it shouldn't be on IE8.
If you need to be fussy about error messages, you could load flowplayer.hlsjs.min.js in a nasty IE conditional comment precluding IE < 9:
```html
<!--[if gt IE 8]>
<script src="//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js"></script>
<![endif]-->
```

**Comment by blacktrash** [comment]
@nnarhinen - I found a way to prevent `default` property literals when webpacking:
```diff
diff --git a/package.json b/package.json
index 1516a1e..1f09a6a 100644
--- a/package.json
+++ b/package.json
@@ -29,6 +29,7 @@
     "babel-core": "^6.5.1",
     "babel-loader": "^6.2.2",
     "babel-preset-es2015": "^6.5.0",
+    "babel-plugin-transform-es3-property-literals": "^6.8.0",
     "jslint": "^0.9.5",
     "webpack": "^1.12.13"
   },
diff --git a/webpack.config.js b/webpack.config.js
index dd0e099..9e87a60 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -37,9 +37,14 @@ module.exports = {
     flowplayer: 'flowplayer'
   },
   module: {
-    loaders: [
-      { test: /hls\.js/, loader: 'babel', query: { presets: ['es2015'] } }
-    ]
+    loaders: [{
+        test: /hls\.js/,
+        loader: 'babel',
+        query: {
+            plugins: ['transform-es3-property-literals'],
+            presets: ['es2015']
+        }
+    }]
   },
   output: {
     path: path.join(__dirname, 'dist'),
```
But the next problem is that webpack uses `Object.setProperty`: https://babeljs.io/docs/usage/caveats/#getters-setters-8-and-below- - any ideas how to circumvent this?

**Comment by xpepermint** [comment]
I'm using Rails and I'm adding this lib into the main `application.js` file using the `require` command. I found a solution for now just by requiring it as the last require statement. If I don't do that, IE8 will not load the rest of the javascript and the player will not work.

**Comment by blacktrash** [comment]
`webpack -p` actually does the same as https://github.com/flowplayer/flowplayer-hlsjs/issues/31#issuecomment-217632885 - but also doesn't solve the `Object.defineProperty` conundrum.

**Comment by Jinkwon** [comment]
This link will help this issue.
https://phabricator.babeljs.io/T7199

**Comment by blacktrash** [comment]
@Jinkwon - hm, that's about quoting `default` etc., that is not a problem anymore.
The persisting problem is that `Object.defineProperty` which you get all over hls.js, e.g.
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
```
That will trigger an IE8 error `Object does not support this action` because IE8 only accepts DOM objects.

**Comment by nnarhinen** [comment]
@blacktrash https://github.com/inexorabletash/polyfill/blob/master/es5.js

If that works, maybe
 * include that in a different flowplayer.hlsjs.ie8.min.js bundle
 * and/or document that library for people that want to support IE8. (Or then just document wrapping hlsjs `<script>` tags in a conditional

**Comment by blacktrash** [comment]
@nnarhinen - thanks, that works (I tried tons of others, but maybe also the wrong way).
Considering that packing it increases min.js only by 4k, what's the disadvantage to just include it by default? afaics it doesn't override without need?

**Comment by blacktrash** [comment]
I'll distribute with packed es5.js by default (Flowplayer supports IE8), and provide flowplayer.hlsjs.es6.min.js for content providers who want to educate their audience to upgrade their browsers ;-)

**Comment by xpepermint** [comment]
Thx! Will the commercial files be the same as the public version?

**Comment by blacktrash** [comment]
@xpepermint - all files of the plugin are free and public ;-)

**Comment by xpepermint** [comment]
Cool! Let me know when I can download the latest version.

**Comment by blacktrash** [comment]
Done.
I have decided not offer a separate version without es5.js - can still be done if the need arises, for the moment this feels like overcomplicating maintenance.

**Comment by xpepermint** [comment]
Huray!

**Comment by blacktrash** [comment]
@xpepermint - unfortunately the polyfill must be removed, see #38, with work around to avoid error reporting.

**Comment by xpepermint** [comment]
@blacktrash thanks for the info.

**Comment by blacktrash** [comment]
@xpepermint - I tried all promising looking polyfills to no avail, if you stumble upon one which works do not hesitate to share ;-)
