### ISSUE TITLE
Hls.js is now support for multi audio stream

### ISSUE THREAD

**Issue by bbaronSVK** [flowplayer/flowplayer-hlsjs#33]
Plese implement hls.js multiaudio streming. More info is [here](https://github.com/videojs/videojs-contrib-hls/blob/master/docs/multiple-alternative-audio-tracks.md)

**Comment by blacktrash** [comment]
@bbaronSVK - this plugin uses the hls.js client. This feature is not yet implemented: https://github.com/dailymotion/hls.js/tree/v0.5.x#not-supported-yet but being worked upon: https://github.com/dailymotion/hls.js/pull/416

**Comment by bbaronSVK** [comment]
sorry
