### ISSUE TITLE
ID3 tags

### ISSUE THREAD

**Issue by BoweryCZ** [flowplayer/flowplayer-hlsjs#34]
Hello,

We are using live stream HLS with embedded ID3 tags. We are able to read these tags in flash player (flowplayer.commercial-3.2.18.swf) using this function:

onNetStreamEvent: function (clip, type, info) {
$("#console").prepend( type + ' : ' + info);
},

Question:           Is it possible to read these tags in HTML5 version with Flash plugin or with flowplayer.hlsjs.min.js?

Thnx

**Comment by blacktrash** [comment]
Have you tried listening to the FRAG_PARSING_METADATA hls.js event: https://github.com/dailymotion/hls.js/blob/v0.5.x/API.md#runtime-events ?

Disclaimer: by lack of a reliable sample I don't know whether and how `data.samples` needs further processing. This may be of interest, also re: differences to flash hls implementation: https://github.com/dailymotion/hls.js/issues/20
