### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer-hlsjs#4]
I do not receive standard flowplayer errors. If there is network error or stream is finished and manifest could not be loaded,I receiving Get errors in console, but there is no Flowplayer error triggered. Player trying reconnect in every 1000 ms. I'm not sure which option in hls.js conf should limit number of reconnection. I tired with fragLoadingMaxRetry and appendErrorMaxRetry, but with no success.

I also can see in debug info: level controller,levelLoadError on live stream, discard

**Comment by blacktrash** [comment]
@popler - try now, with:
```js
hlsjs: {
  strict: true
}
```
in your configuration. Note that this has no effect on generic HLS playback. The default behaviour is similarly lenient.

**Comment by popler** [comment]
Not working nothing change. Problem is in line 'else if (level && level.details && level.details.live) {
            _utilsLogger.logger.warn('level controller,' + details + ' on live stream, discard');
          }'
in hls.js. There was a change due to issue number #31. But after this change all network errors are non fatal. I tried to comment out this line, of course:) Errors are shown as I expected after this. But even short problem with network is breaking live stream and it could not be resumed.

**Comment by popler** [comment]
I receive error Uncaught InvalidStateError: Failed to execute 'endOfStream' on 'MediaSource': The MediaSource's readyState is not 'open'. after this live was commented out. Even if next packet can be load, stream is broken in player.

**Comment by popler** [comment]
I added logging non fatal errors to flowplayer-hlsjs and it's working almost I expected:)

**Comment by blacktrash** [comment]
@popler - if you identify or isolated a problem with hls.js, not hlsjs, the Flowplayer plugin, please take it to the hls.js bug tracker: https://github.com/dailymotion/hls.js/issues

Closing this for now.
