### ISSUE TITLE
Playback broken on latest ios update

### ISSUE THREAD

**Issue by cjhmdm** [flowplayer/flowplayer-hlsjs#45]
"html5: Video not properly encoded" error on latest ios update

**Comment by blacktrash** [comment]
So far iOS did not support MediaSource and therefore also not hlsjs - there's a check at the plugin page for instance: https://flowplayer.org/docs/plugins.html#hlsjs-compatibility
Does it still say 'No'? - Then you'd have problems with native playback.

**Comment by janiszie** [comment]
I can confirm that iOS10 through flowplayer implementation doesn't play videos - error as stated in first post, but I also came to conclusion that this is some native playback problem case (?).

**Comment by blacktrash** [comment]
Does this happen with our demos too?

**Comment by janiszie** [comment]
No, it doesn't. I checked both encrypted and non-encrypted versions for hls. So it seems that there ir some problem with backend, in our case nginx-vod maybe is messing up. Thanks for point!

**Comment by blacktrash** [comment]
We also offer quick cross-check testing of native playback here: http://demos.flowplayer.org/videotest/
