### ISSUE TITLE
Last release version has broken Signed Cookie

### ISSUE THREAD

**Issue by DrySs** [flowplayer/flowplayer-hlsjs#46]
This commit https://github.com/flowplayer/flowplayer-hlsjs/commit/3471d29a74882bc5e7530103f045a2f5a37be3bd#diff-94f13f3a9cd67338f3d3e142b0a9708dL310 has broken Signed Cookie for CloudFront.

We use following settings:
 params.hlsjs = { xhrSetup: function(xhr, url) { xhr.withCredentials = true; } };

Which is no more used with latest release. This is a big problem as well as you do not provide any tags to rollback on previous version, we have to use last version from online repository.

**Comment by blacktrash** [comment]
Very sorry about that. Reverted that change.
Should be ok now. Unless it was actually caused by a breaking change in hls.js v0.6.2-7. Will check that now.

**Comment by blacktrash** [comment]
@DrySs - I checked with `loader`, `pLoader` and other functions, but overlooked https://github.com/dailymotion/hls.js/issues/697
