### ISSUE TITLE
Playlist resume from first too late to prevent Chrome error message

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer-hlsjs#52]
Another "half-html5-engine" issue (same for dashjs):
On resume.fromfirst Chrome complains:
```
flowplayer.hlsjs.min.js:22 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
```
With separate unminified components it's:
```
buffer-controller.js:92 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
```
Timing issue: Overriding the click handler with sth like this on finish
```
flowplayer.bean.one(flowplayer.common.find('.fp-ui', root)[0], "click.fromfirst', function () {
  api.play(0);
  return false;
});
```
does the job - but only for clicks obviously.

Will check whether anything could be done in hls.js, but I doubt it.

@nnarhinen - as usual, bright ideas are welcome ;-)

**Comment by nnarhinen** [comment]
is this same as flowplayer/flowplayer/issues#1063 ?

**Comment by blacktrash** [comment]
Duh, it's a core issue already, short term memory loss: https://github.com/flowplayer/flowplayer/issues/1063
Closing for the moment.
