### ISSUE TITLE
Configuration muted: true, auto_play: true does not work 100%

### ISSUE THREAD

**Issue by BoweryCZ** [flowplayer/flowplayer-hlsjs#53]
In several cases, when video start to hear the audio for a split second. Is there a way to set the player had turned off the sound immediately after the start?

We use flowplayer + hlsjs in this configuration:
`flowplayer("#player", {
    volume: 0,
    muted: true,
    autoplay: true,
    live: true,
     clip: {
                sources: [{
                    type: "application/x-mpegurl",
                    src: opt.hls
                }]
            }
        })
                
`

**Comment by BoweryCZ** [comment]
We have changed the way to retrieve the player and it seems to be alright.

`
flowplayer("#player", {
            muted: true,
           autoplay: false,
            live: true,
            clip: {
                sources: [{
                    type: "application/x-mpegurl",
                    src: opt.hls
               }]
            }
        })
                
        .on("ready", function (e, api, video) {
                               api.mute(true);
                               api.play();
        })

`

**Comment by blacktrash** [comment]
Actually this should not happen, there should not be a need for a workaround - I somewhat expect it rather to happen with the workaround.
@BoweryCZ - if you don't mind, could you be more specific and investigate a bit further on your end (I so far can't repro):
- is this only happening with hlsjs, or also with flash hls, and, most importantly, in native playback?
- is this happening with specific streams?
- is this happening in specific browsers, browser versions, on specific platforms?

Re-opening for further investigation.

**Comment by blacktrash** [comment]
Possibly related: https://github.com/flowplayer/flowplayer/issues/1073

**Comment by blacktrash** [comment]
Fixed via https://github.com/flowplayer/flowplayer-hlsjs/commit/96947117a295b9e2b2aaa76648bc412b2fb746af

**Comment by josh-sachs** [comment]
@blacktrash I don't see this fix anymore in the latest release.  I found this ticket experiencing the same issue... pasting in the change in #9694711 appears to resolve.

**Comment by blacktrash** [comment]
@josh-sachs - thanks for bringing this up. Oversight/forgetfulness of mine, sorry.
Should be fixed again.
