### ISSUE TITLE
hlsjs: Video not properly encoded

### ISSUE THREAD

**Issue by akovacs123** [flowplayer/flowplayer-hlsjs#59]
I have seen reported this problem many times and seems like you fixed them all. However, with latest version of hlsjs + using Wowza Streaming Engine 4.5 the same problem appears.

When I try to seek to a point which has not been yet downloaded (beyond buffer indicator) I get this:

"hlsjs: Video not properly encoded"

Although, seeking to a point that is already downloaded works fine. I tried two fixes, none of them worked:
- add codec and resolution to the m3u8 playlist
- converted the mp4 file to move the moov atom to the begining of the file

My m3u8 looks like this:

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=634832,CODECS="avc1.66.21,mp4a.40.2",RESOLUTION=484x272
chunklist.m3u8`

I would be happy to send you my stream URL, but do now want to disclose here... let me know what to do.

**Comment by blacktrash** [comment]
@akovacs123 - does the stream work in the hls.js sample player with the currently used version 0.6.14 in the plugin: http://streambox.fr/mse/hls.js-0.6.14/demo/ ?

**Comment by akovacs123** [comment]
@blacktrash: wow, it works. I used "strict: true" that made the error pop-up. Without this option, it is okay now. Thanks for pointing to the sample player.

**Comment by blacktrash** [comment]
@akovacs123 - depending on what exactly you want, playing with the (not so new) `recoverMediaError` and `recoverNetworkError` options may be useful for testing. With obviously greater care in production: https://flowplayer.org/docs/plugins.html#hlsjs-options
