### ISSUE TITLE
npm: only retrieves latest hls.js dist update

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer-hlsjs#6]
While package.json says:
```js
"hls.js": "git://github.com/dailymotion/hls.js#c77153d5d6db48c36b5752c85a6ef36aa3585365"
```
The version used is actually older: https://github.com/dailymotion/hls.js/commit/525bb79c8f029470d262c796f00990e32adee894

@nnarhinen - this is not ideal, effectively hls.js is now downgraded. I had used a manually built version of hls.js. The version in package.json is not indicative of the version actually used.

Maybe we should at least re-instate hls.js and hls.min.js in the repo for our deployed release. If someone wants to use the builder, he's free to do so, but it would not be officially supported.
Also I would make the version in package.json point to an actual change to dist.

@nnarhinen - other ideas?

**Comment by nnarhinen** [comment]
```
$ rm -rf node_modules
$ npm install
$ grep "_resolved" node_modules/hls.js/package.json
"_resolved": "git://github.com/dailymotion/hls.js#c77153d5d6db48c36b5752c85a6ef36aa3585365",
```

seems to checkout the right commit hash for me

**Comment by blacktrash** [comment]
Sure, but that wasn't the point. The point was:
1. that it downgraded hls.js and hls.min.js which were manual more recent builds
2. that we depend on when hls.js/dist is updated - which is probably fine in this case because it's updated quite often, but would not be advisable for instance with dash.js

If for instance we use the plugin with Drive, we cannot make a quick hotfix which reflects itself in our repo.

It's probably fine in this case.

**Comment by nnarhinen** [comment]
Hmm. Ok, maybe it would be wise then to re-instate the hls.js and hls.min.js in the repo and make sure the hash in package.json matches the hash from where those two files are built from.

In a commonjs environment hls.js/dist files are not read at all.

**Comment by blacktrash** [comment]
Let's go with hls.js builds for the moment. We can change policy if need arises.
