### ISSUE TITLE
Duplicated error message when the master playlist is available but not the variants

### ISSUE THREAD

**Issue by mgara** [flowplayer/flowplayer-hlsjs#61]
Hello, I can see double errors on the screen "hlsjs: Video file not found" 
and the error event is fired twice when the master playliste is available but not the variants(multiple bitrates)
Is it normal ?
also I had a bigger issue when I was using the release version ... so I switched to the minimal version : is that normal ?  Well apparently the minimal version is not the same as the full version of the hlsjs : the full version loads the flash engine as if the hlsjs is not even loaded.
Thanks.

**Comment by mgara** [comment]
Player view : basically double messages : 
![player](https://cloud.githubusercontent.com/assets/6472786/22663337/35b33452-ec7a-11e6-9522-ad31a9c62d67.PNG)
console view shows 
![console](https://cloud.githubusercontent.com/assets/6472786/22663425/8bb9a7c8-ec7a-11e6-8374-c5eba46261f6.PNG)

**Comment by blacktrash** [comment]
1. Double error message:
I can observer this as well, it's a Flowplayer 7 thing; it doesn't happen with Flowplayer 6 which bails out quicker. I'll file a report against core if I don't forget and you don't beat me to it.
That being said, it can be dealt with, as you can see in this demo:
http://flowplayer.org/api/live-check.html
Version 6 for comparison:
http://flowplayer.org/v6/api/live-check.html

Your other question is not clear. The github README - https://github.com/flowplayer/flowplayer-hlsjs#features - tells you the hls.js version (currently v0.6.20) packed into the latest plugin version, which shoud be loaded as per https://flowplayer.org/docs/plugins.html#hlsjs-assets from `//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js`
Both the github README and the plugin page point to the hls.js docs of the currently packed version etc.
What exactly is the problem?

**Comment by blacktrash** [comment]
I think I was able to solve this in the plugin.
