### ISSUE TITLE
flowplayer-hlsjs does not work well with webpack

### ISSUE THREAD

**Issue by huiyiqun** [flowplayer/flowplayer-hlsjs#62]
I have installed flowplayer and flowplayer-hlsjs like following:

```
npm install flowplayer flowplayer/flowplayer-hlsjs
```

and load them like [that](https://github.com/flowplayer/flowplayer-hlsjs/tree/6ac3ed955be757e4f4586fb153c34fea993a0d8e#commonjs) descriped in README.

The problem is that when building the project with webpack, I have following error:

```
ERROR in ./~/flowplayer-hlsjs/flowplayer.hlsjs.js
Module not found: Error: Can't resolve 'hls.js/lib/index.js' in '/home/huiyiqun/Develop/iptv/node_modules/flowplayer-hlsjs'
 @ ./~/flowplayer-hlsjs/flowplayer.hlsjs.js 882:51-81
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/HLSPlayer.vue
 @ ./src/HLSPlayer.vue
 @ ./src/route.js
 @ ./src/main.js
```

I replace `hls.js/lib/index.js` in [this line](https://github.com/flowplayer/flowplayer-hlsjs/blob/6ac3ed955be757e4f4586fb153c34fea993a0d8e/flowplayer.hlsjs.js#L882) with `hls.js/dist/hls.js`, and it works.

I'm confused, is this a bug introduced by a new version of hls.js?

**Comment by blacktrash** [comment]
hls.js changed the system in v7.0.0 https://github.com/dailymotion/hls.js/pull/934
The current system only works until hlsjs v1.0.5

**Comment by blacktrash** [comment]
See:
https://github.com/flowplayer/flowplayer-hlsjs/issues/43
https://github.com/flowplayer/flowplayer-hlsjs/pull/58
https://github.com/dailymotion/hls.js/issues/688
or
https://github.com/dailymotion/hls.js/pull/944
etc. etc.

@huiyiqun - you can also do:
```js
module.exports = extension.bind(undefined, require('hls.js'));
```
with the same warning, it will just use a copy of the dist file.

For Flowplayer we most likely for now could just load the new 'light' version:
```js
module.exports = extension.bind(undefined, require('hls.js/dist/hls.light.js'));
```
because Flowplayer does currently not support multiple audio tracks and hls subtitles.

I will do that until there's a solution (if ever).

**Comment by huiyiqun** [comment]
For there is no hls.js v1.0.5 in npm at all, it's difficult for webpack user to use flowplayer-hlsjs.

Is it possible to include any workaround in next release so that I could build my project without editing files in `node_modules`?

**Comment by blacktrash** [comment]
@huiyiqun - it should now work: https://github.com/flowplayer/flowplayer-hlsjs/commit/530bc1ce61955b2288579df5e8b6b14ae7390a29

**Comment by huiyiqun** [comment]
Thanks

**Comment by blacktrash** [comment]
Re-opening for investigation whether and how it can be built from source with hls.js v7.0.0+

**Comment by blacktrash** [comment]
The recommended way is still not to build from source.
