### ISSUE TITLE
AES encryption and Chromecast/AirPlay

### ISSUE THREAD

**Issue by janiszie** [flowplayer/flowplayer-hlsjs#65]
I hope it's the right topic.

We are using Flowplayer 7.0.2 with HLS.JS and AES-128 encryption.  Bought upgrade licence from FP6 to specifically get Chromecast/AirPlay feature. 

Actually player sees that there is Chromecast on local network, allows to press icon, starts to do something on tv screen (blue chromecast icon shows up and loading bar) but streaming doesn't start. 

I also checked https://flowplayer.blacktrash.org/hls-crypt/ - the same behaviour. 

I didn't see any disclaimer on feature list that it won't work. Streaming it self is working fine on website and iOS.

**Comment by blacktrash** [comment]
Is your receiver hosted on https? See: https://code.google.com/p/google-cast-sdk/issues/detail?id=426
What happens if you do not load the hlsjs plugin: https://flowplayer.blacktrash.org/hls-crypt/?hlsjs=false

**Comment by bbbo** [comment]
@blacktrash @nnarhinen I can confirm this: doesn't work with or without the hlsjs plugin.

**Comment by blacktrash** [comment]
Maybe it's setup specific, I'm now allowing goog.net.XhrIo as referer as well in .htaccess for drive-crypt-key2.php - @bbbo, can you test again?
Maybe localhost must be allowed too.
Make sure your receiver is https hosted.

**Comment by bbbo** [comment]
I'm using the standard Chromecast input (through cast stick) , I don't see how I could influence the receiver...

**Comment by nnarhinen** [comment]
This would have to be tested with a setup where the key file is not secured at all (in other words: downloadable for everyone everywhere). If it works, then it's about securing the key. The only option I coul think of would be to have the manifests / key urls generated dynamically (signed urls or such)

**Comment by blacktrash** [comment]
@nnarhinen, @bbbo - I have removed  the cookie blocker for testing purposes at https://flowplayer.blacktrash.org/hls-crypt/ for the next couple of days.

**Comment by bbbo** [comment]
didn't help unfortunately. The NASA stream on http://demos.flowplayer.org/api/hlsjs.html works fine though.

**Comment by blacktrash** [comment]
The NASA stream is not encrypted.

**Comment by bbbo** [comment]
Yes I know, I just wanted to emphasize it's not a principal HLS / hlsjs problem.

**Comment by blacktrash** [comment]
I can try with a given IV at some point.

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/24025537/b38d1c50-0ac3-11e7-8374-46014ab5106d.png)

The key is not accessible for public yet. We should check with a stream with no restrictions at all. Just to make sure ChromeCast is capable to decrypt. Then it's just the matter of securing the key.

**Comment by blacktrash** [comment]
Should be now:
```
$ curl -I https://flowplayer.blacktrash.org/hls-crypt/drive-
crypt-key2.php
curl: (6) Could not resolve host: http
HTTP/1.1 200 OK
Date: Fri, 17 Mar 2017 08:50:16 GMT
Server: Apache (custom)
Cache-Control: no-store
Upgrade: h2,h2c
Connection: Upgrade
Vary: User-Agent
Content-Type: binary/octet-stream
```
Althought the referrers shouldn't matter - or maybe I should have re-added goog.net.XhrIo

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/not-indexed/encrypted-bauhaus.html

This works on my Chromecast, so I guess it's still something to do with the way you are serving the key file. Can you make your encrypted demo use `conf.applicationId = '141F324D'` so I can debug it in chrome.

**Comment by blacktrash** [comment]
@nnarhinen - done, including disabling all php related code.
The only php thing left is the key file read via php. I can change that as well if needed.

**Comment by blacktrash** [comment]
@nnarhinen - http://demos.dev94.flowplayer.us/not-indexed/encrypted-bauhaus.html does not load hlsjs?
Please use https://flowplayer.blacktrash.org/hls-crypt/test.html - when I add `applicationId` to the player config the demo does not work in normal circumstances.

**Comment by nnarhinen** [comment]
> Please use https://flowplayer.blacktrash.org/hls-crypt/test.html - when I add applicationId to the player config the demo does not work in normal circumstances.

How does it not work?

> http://demos.dev94.flowplayer.us/not-indexed/encrypted-bauhaus.html does not load hlsjs?

This has nothing to do with HLSjs (it's actually in wrong repo)

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/24094020/7478c7be-0d5f-11e7-96d0-5a7bd8b67791.png)

Can you fix the syntax please.

**Comment by blacktrash** [comment]
@nnarhinen - yikes, sorry, done for https://flowplayer.blacktrash.org/hls-crypt/test.html

**Comment by nnarhinen** [comment]
Sorry, it should be `conf.chromecast.applicationId`.. Misread the code..

**Comment by blacktrash** [comment]
Updated.

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/24096355/022f3408-0d6a-11e7-98ff-1b1d1707d4a6.png)

**Comment by blacktrash** [comment]
Added:
```
$ curl -I https://flowplayer.blacktrash.org/hls-crypt/drive-crypt-key2.php
HTTP/1.1 200 OK
Date: Mon, 20 Mar 2017 10:50:09 GMT
Server: Apache (custom)
Access-Control-Allow-Origin: *
Cache-Control: no-store
Upgrade: h2,h2c
Connection: Upgrade
Vary: User-Agent
Content-Type: binary/octet-stream
```

**Comment by nnarhinen** [comment]
Works now.

**Comment by blacktrash** [comment]
How about https://flowplayer.blacktrash.org/hls-crypt/  now?

**Comment by blacktrash** [comment]
Changed to:
```
Access-Control-Allow-Origin: https://www.gstatic.com
Access-Control-Allow-Methods: GET
```
I may still have to update the referer pattern in .htaccess, please test.

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/24272972/8b90656c-1028-11e7-959d-000c843b2a59.png)

**Comment by nnarhinen** [comment]
Are you using the cookie check again? The cookies can't be transferred. Will try to look if using a custom receiver application would help with this.

**Comment by blacktrash** [comment]
Yes. I've enabled the cookie check again to find out the lowest common denominator to make this work.
Maybe it helps when I circumvent the cookie check with a referer from www.gstatic.com.
Thanks for testing.

**Comment by blacktrash** [comment]
@nnarhinen 
```
$ curl -i \
-H 'Origin: https://www.gstatic.com' \
-H 'referer: https://flowplayer.blacktrash.org/hls-crypt/' \
https://flowplayer.blacktrash.org/hls-crypt/drive-crypt-key3.php | sed -e '/^\s*$/q'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16    0    16    0     0     85      0 --:--:-- --:--:-- --:--:--    85
HTTP/1.1 200 OK
Date: Fri, 24 Mar 2017 17:29:57 GMT
Server: Apache (custom)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Access-Control-Allow-Origin: https://www.gstatic.com
Access-Control-Allow-Methods: GET
Cache-Control: no-store
Set-Cookie: PHPSESSID=2koaq933tl1u7dt507atmopsu6; path=/
Upgrade: h2,h2c
Connection: Upgrade
Vary: Accept-Encoding,User-Agent
Transfer-Encoding: chunked
Content-Type: binary/octet-stream
```

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/24315823/29073388-10f2-11e7-9d75-dfe240cee3a9.png)

**Comment by nnarhinen** [comment]
> HLS_NETWORK_INVALID_SEGMENT	315	The HLS segment received for processing is neither a TS nor an mp4 AAC segment. Could be MPL bug or configuration on receiver app bug.	Developers need to validate that their segments are either TS or AAC.

**Comment by nnarhinen** [comment]
How does the stream differ from edge.flowplayer.org/encrypted-bauhaus/84049.m3u8

**Comment by blacktrash** [comment]
It differs in 2 ways:
1. it's a different video ;-)
2. audio is a separate track

It's the same as edge.flowplayer.org/drive.m3u8 (which passes, like all our streams the Apple mediastreamvalidator test) - only encrypted.
Certainly all segments are TS.
I'll switch back to a stream with audio not in EXT-X-MEDIA.

**Comment by blacktrash** [comment]
@nnarhinen - https://flowplayer.blacktrash.org/hls-crypt/ now has a different stream without multiplexing.

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/24316564/90cc8888-10f7-11e7-9a00-5ff5875e1d01.png)

This is from the plain drive.m3u8 without encryption. It might be Chromecast is not capable of separate audio track?

**Comment by nnarhinen** [comment]
https://flowplayer.blacktrash.org/hls-crypt/ Now works on chromecast:

![2017-03-25 01 09 51](https://cloud.githubusercontent.com/assets/265438/24316592/d6b0dec6-10f7-11e7-9e04-656294792ae5.jpg)

**Comment by blacktrash** [comment]
Could you quickly check (unencrypted):
1. https://flowplayer.blacktrash.org/fp7/hls.html (multiplex with a tiny tweak)
2. https://flowplayer.org/standalone/plugins/dashjs.html (MPEG-DASH, I guess this doesn't work at all, as chromecast doesn't use hlsjs apparently, so it won't use dashjs either)

Can you also check whether it supports MediaSource at all?

**Comment by nnarhinen** [comment]
https://flowplayer.blacktrash.org/fp7/hls.html does not work
https://flowplayer.org/standalone/plugins/dashjs.html works

Our current implementation only passes the media location to chromecast (path to source `src`). It's up to the chromecast receiver to handle playing. If we would write a custom receiver application for chromecast, then there would be more room for tweaking (like maybe using hls.js etc)

**Comment by blacktrash** [comment]
@nnarhinen - thank you. One last capability test:
https://flowplayer.blacktrash.org/fp7/hls.html - now with non-multiplexed byterange request based stream.
Thank you.

**Comment by blacktrash** [comment]
> Our current implementation only passes the media location to chromecast (path to source `src`). It's up to the chromecast receiver to handle playing. If we would write a custom receiver application for chromecast, then there would be more room for tweaking (like maybe using hls.js etc)

A receiver app would have to be installed by the viewer prior to viewing, correct?
If yes, then this is a nice extra for the cases where the publisher believes/assumes their audience is willing to take on this delay before gratification, i.e., instant "plugin and play" is not relevant (hardly a common case).

**Comment by nnarhinen** [comment]
> A receiver app would have to be installed by the viewer prior to viewing, correct?

Nope. It's more like the "website" the chromecast device requests where the video is then "injected". That's the `chromecast.applicationId` in our configuration. (Not yet documented as it should stay for now).

**Comment by nnarhinen** [comment]
https://flowplayer.blacktrash.org/fp7/hls.html works on chromecast

**Comment by blacktrash** [comment]
Thanks.

**Comment by blacktrash** [comment]
So alternate EXT-X-MEDIA is the only thing which is not supported. Probably also not fMP4 yet.
Just to be sure: https://flowplayer.blacktrash.org/fp7/hls.html now with multiplexed byte-range (should not work).
If this is the case injecting hls.js would be a very nice to have.

**Comment by blacktrash** [comment]
@nnarhinen - if you could just check https://flowplayer.blacktrash.org/fp7/hls.html one more time - I expect this not to work, but would like to be 100% sure.
Then this can be closed.
Thanks.

**Comment by nnarhinen** [comment]
https://flowplayer.blacktrash.org/fp7/hls.html does not work now in chromecast

**Comment by blacktrash** [comment]
Thanks.

**Comment by janiszie** [comment]
Guys, I tried to follow you discussion and problem solving, but in the end didn't find answer to my original question.

Does Flowplayer support Chromecast/Airplay with AES encryption?

**Comment by nnarhinen** [comment]
It does, but if your key serving mechanism uses cookies to secure the key it won't work without a custom chromecast application at least.
