### ISSUE TITLE
After api.unload() the hlsjs plugin continue to request m3u8 playlist and ts chunks. 

### ISSUE THREAD

**Issue by mgara** [flowplayer/flowplayer-hlsjs#66]
After api.unload() the hlsjs plugin continue to request m3u8 playlist and ts chunks.  

STEPS to reproduce: 

api.load(); -> starts Playback
api.unload(); -> stops Playback but the hlsjs continue requesting chunks

(this is a live feed context)

This could be a feature to enable a quick resume after a "load" I'm not sure about it.

**Comment by blacktrash** [comment]
If you really unload the player this works fine, but you can only "truly" unload the player if it's a splash setup, see https://flowplayer.org/docs/api.html#methods
Are you using a splash setup?

Not sure what exactly you want, but this #57 looks related.

**Comment by blacktrash** [comment]
No feedback. Closing.
