### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by lhermann** [flowplayer/flowplayer-hlsjs#67]
Chrome is refusing to play the video with the following error:

`Mixed Content: The page at 'https://example.com/test.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.com/video.mp4/index-v1-a1.m3u8'. This request has been blocked; the content must be served over HTTPS.`

The hls resource is also available via https, but the plugin seems not to check the protocol, tries to request the insecure resource and gets blocked by the browser.

Is there any setting to avoid this issue?

**Comment by bbbo** [comment]
Please ask usage questions in the forums.

If you configure a http link, the browser (or any player) will fulfill that request. Simply configure the source without protocol ( ie // instead of http(s)://

**Comment by blacktrash** [comment]
@lhermann - https://flowplayer.org/docs/setup.html#https ;-)
