### ISSUE TITLE
ABR laoding error

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer-hlsjs#7]
I have problem with ABR live stream. If I have insufficient bandwith to load best quality on start playing the stream, I receive Network_ERROR:FRAG_LOAD_TIMEOUT. And it looks like player still trying to receive the same quality. Probably it should try to take next, lower level. Player stack in loading state in situation like this.
I'm not sure it is problem with flowplayer-hlsjs or hls.js.

**Comment by blacktrash** [comment]
As per https://github.com/flowplayer/flowplayer-hlsjs#debugging test in the hls.js sample player for comparison: http://dailymotion.github.io/hls.js/demo/

**Comment by blacktrash** [comment]
Not heard back, closing.
