### ISSUE TITLE
It can work well in Safari,but it can't work in Chrome

### ISSUE THREAD

**Issue by verney2016** [flowplayer/flowplayer-hlsjs#74]
I write this code:
```
clip: {
sources: [{
                    type: "application/x-mpegurl",
                    src: "https://dn-chop.qbox.me/xxx/video/docker.mp4"
                }, {
                    type: "video/mp4",
                    src: "https://dn-chop.qbox.me/xxx/video/docker.mp4"
                }]
}
```

It can't play in chrome,but it can work well in safari.

**Comment by blacktrash** [comment]
MP4 != HLS - just by _declaring_ an MP4 as HLS, it does not _become_ HLS.
See: https://flowplayer.org/docs/setup.html#hls
And please use the public forum - https://flowplayer.org/forum/ - to ask usage questions, unless you are certain that there is a bug. Thank you.
