### ISSUE TITLE
do you need to include hls.js as well with this plugin?

### ISSUE THREAD

**Issue by kellyrmilligan** [flowplayer/flowplayer-hlsjs#8]
the docs on the site say that its included with the plugin, but the repo says it requires hls.js?  trying to use it with webpack, and at the end of the plugin it clearly tries to require in both flow player and hls.js directly or on the window object.

**Comment by nnarhinen** [comment]
With the CommonJS -approach you should use NPM to install both this plugin and flowplayer: 

```
npm install flowplayer/flowplayer-hlsjs flowplayer
```

It will pull hls.js in as dependency. Then you can use it by requiring:

```js
var flowplayer = require('flowplayer');
require('flowplayer-hlsjs'); // Plugin is injected
```

We also offer a pre-bundled version with hls.js packed in: http://releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js

This version can be just included in a script tag and you don't need to include hls.js yourself. An example can be found from http://demos.flowplayer.org/api/hlsjs.html

**Comment by kellyrmilligan** [comment]
If you have the commercial version of flow player is it ok to install flow player from npm and just provide the key then?  That was the main issue I was having was having the pre bundled versions and using webpack with them.
