### ISSUE TITLE
npm install is not working

### ISSUE THREAD

**Issue by rameshvishnoi90904** [flowplayer/flowplayer-hlsjs#86]
npm install gives error as git not found

**Comment by blacktrash** [comment]
What exactly are you doing? Please provide more details. I doubt that this is related to this plugin.

If you don't have git installed, you must have obtained the plugin source code from a release zip/tarball. package.json does not contain any git:// URLs, so just to verify, I just git out of my $PATH, and ran npm install inside the source directory w/o probs.

**Comment by blacktrash** [comment]
Closing due to lack of further information.
