### ISSUE TITLE
hlsjs: Video file not found

### ISSUE THREAD

**Issue by Instacker** [flowplayer/flowplayer-hlsjs#95]
I have litle problem with my m3u8 Video - some how the player isn't able to find it , even it url is correct. So i tested it with demo file from flowplayer.org and that works. Only my files dosn't seem to work. The problem is: I'm very new to hls streaming and I need some help. - [The test page](https://en.instacker.com/article/geomorphology-id=196)

[My M3U8 File](https://instacker.com/upload/canyonlands_national_park_utah_usa/canyonlands_national_park_utah_usa.m3u8)

My setup:

		
		
    <div class="flowplayer" data-ratio="0.5625">
 
        <video>
            <source type="application/x-mpegurl" src="https://instacker.com/upload/canyonlands_national_park_utah_usa/canyonlands_national_park_utah_usa.m3u8">
        </video>
		 
    </div>

[Full Video Download](https://drive.google.com/file/d/0B3ZePi7aUKD2Tzh0cTF3OTlpY3M/view?usp=sharing) I converted a mp4 file to the m3u8 format with [Vodobox HLS Encoder](http://www.vodobox.com/index.html?content=build_player.html)

**Comment by blacktrash** [comment]
@Instacker - thank you for the links and demo page.

Your stream is not delivered with the required CORS headers: https://flowplayer.com/docs/plugins.html#hlsjs-server-side
Aside: for the Flash HLS failover the crossdomain.xml policy file at your server root is missing: https://flowplayer.com/docs/setup.html#cross-domain

As this is a usage question, and of common interest, please ask these kind of questions in our public forum https://flowplayer.com/forum in the future. Thanks.

**Comment by Instacker** [comment]
Oh sry for that - I wasn't shure where to ask. But I relly appreciate your Help thanks
