### ISSUE TITLE
Unminified script fails in browser environment due to call to require()

### ISSUE THREAD

**Issue by gmathis** [flowplayer/flowplayer-hlsjs#96]
Since 6247881 ("Decode unicode binary to UTF-16 in IE"), loading the unminified debug script in the browser fails:

`<script src="//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.js"></script>`

The script makes a [call](https://github.com/flowplayer/flowplayer-hlsjs/commit/62478813047f53f116437fb25e13003d83c0f0cb#diff-94f13f3a9cd67338f3d3e142b0a9708dR52) to `require()` that fails in the absence of a module loader.

**Comment by blacktrash** [comment]
The full plugin needs the slimmed down text-encoding lib.
You can either use the light script from releases.flowplayer.org/hlsjs/flowplayer.hlsjs.light.js - or, if you need the full plugin features, you have to build yourself: https://github.com/flowplayer/flowplayer-hlsjs#building-the-plugin

**Comment by gmathis** [comment]
Thanks for the update and clarification.
